owner: AnandChowdhary
repo: status
sites:
  - name: AnandChowdhary.com
    url: https://anandchowdhary.com
  - name: SukritiKapoor.com
    url: https://sukritikapoor.com
  - name: Test
    url: https://webhook.site/f5a5a4c7-1a86-408e-ab9a-13f019581a78
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "hello": "world" }'
assignees:
  - AnandChowdhary
notifications:
  - type: slack
    channel: C01XQ3U9M9P
status-website:
  baseUrl: /status
  logoUrl: https://anandchowdhary.com/android-chrome-192x192.png
  name: Anand's Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
